MSG_TALKER_TRANSLATE = 'MSG_TALKER_TRANSLATE'
MSG_LOVE_ME_REQUEST = 'MSG_LOVE_ME_REQUEST'
MSG_LOVE_ME_SUBMIT = 'MSG_LOVE_ME_SUBMIT'
MSG_WX_REQUEST = 'MSG_WX_REQUEST'
MSG_WX_EVENT_FOLLOW = 'MSG_WX_EVENT_FOLLOW'
MSG_WX_EVENT_IGNORE = 'MSG_WX_EVENT_IGNORE'

